name: Build Docs
on: ~

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Judge Status
      if: contains(github.event.head_commit.message, '[builddocs]')
      run:
        - uses: actions/checkout@v2
        - uses: julia-actions/setup-julia@v1
          with:
            version: '1.6'
        - uses: julia-actions/cache@v1
        - uses: julia-actions/julia-buildpkg@v1
        - run: |
          julia -e '
            using Pkg
            Pkg.add(name="DoctreePages", version="1.2")
            using DoctreePages
            github_action()
          '